//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioRUT.WS_ServicesRUTPruebas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcomerReq", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_InscripcionRUT.Models")]
    [System.SerializableAttribute()]
    public partial class ProcomerReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServicioRUT.WS_ServicesRUTPruebas.ActividadEconomica ActividadEconomicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServicioRUT.WS_ServicesRUTPruebas.Apoderado ApoderadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServicioRUT.WS_ServicesRUTPruebas.Persona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServicioRUT.WS_ServicesRUTPruebas.Representante RepresentanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioRUT.WS_ServicesRUTPruebas.ActividadEconomica ActividadEconomica {
            get {
                return this.ActividadEconomicaField;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadEconomicaField, value) != true)) {
                    this.ActividadEconomicaField = value;
                    this.RaisePropertyChanged("ActividadEconomica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioRUT.WS_ServicesRUTPruebas.Apoderado Apoderado {
            get {
                return this.ApoderadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApoderadoField, value) != true)) {
                    this.ApoderadoField = value;
                    this.RaisePropertyChanged("Apoderado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioRUT.WS_ServicesRUTPruebas.Persona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioRUT.WS_ServicesRUTPruebas.Representante Representante {
            get {
                return this.RepresentanteField;
            }
            set {
                if ((object.ReferenceEquals(this.RepresentanteField, value) != true)) {
                    this.RepresentanteField = value;
                    this.RaisePropertyChanged("Representante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActividadEconomica", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_InscripcionRUT.Models")]
    [System.SerializableAttribute()]
    public partial class ActividadEconomica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoActividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroCantonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtrasSenasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrCantonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoFijoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoActividad {
            get {
                return this.CodigoActividadField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoActividadField, value) != true)) {
                    this.CodigoActividadField = value;
                    this.RaisePropertyChanged("CodigoActividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioField, value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroCanton {
            get {
                return this.NroCantonField;
            }
            set {
                if ((this.NroCantonField.Equals(value) != true)) {
                    this.NroCantonField = value;
                    this.RaisePropertyChanged("NroCanton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroDistrito {
            get {
                return this.NroDistritoField;
            }
            set {
                if ((this.NroDistritoField.Equals(value) != true)) {
                    this.NroDistritoField = value;
                    this.RaisePropertyChanged("NroDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroProvincia {
            get {
                return this.NroProvinciaField;
            }
            set {
                if ((this.NroProvinciaField.Equals(value) != true)) {
                    this.NroProvinciaField = value;
                    this.RaisePropertyChanged("NroProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtrasSenas {
            get {
                return this.OtrasSenasField;
            }
            set {
                if ((object.ReferenceEquals(this.OtrasSenasField, value) != true)) {
                    this.OtrasSenasField = value;
                    this.RaisePropertyChanged("OtrasSenas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrCanton {
            get {
                return this.StrCantonField;
            }
            set {
                if ((object.ReferenceEquals(this.StrCantonField, value) != true)) {
                    this.StrCantonField = value;
                    this.RaisePropertyChanged("StrCanton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrDistrito {
            get {
                return this.StrDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.StrDistritoField, value) != true)) {
                    this.StrDistritoField = value;
                    this.RaisePropertyChanged("StrDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrProvincia {
            get {
                return this.StrProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrProvinciaField, value) != true)) {
                    this.StrProvinciaField = value;
                    this.RaisePropertyChanged("StrProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoFijo {
            get {
                return this.TelefonoFijoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoFijoField, value) != true)) {
                    this.TelefonoFijoField = value;
                    this.RaisePropertyChanged("TelefonoFijo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Apoderado", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_InscripcionRUT.Models")]
    [System.SerializableAttribute()]
    public partial class Apoderado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoClasePersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetallePoderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreApoderadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroCantonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtrasSenasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrCantonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoMovilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTipoClasePersona {
            get {
                return this.CodTipoClasePersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoClasePersonaField, value) != true)) {
                    this.CodTipoClasePersonaField = value;
                    this.RaisePropertyChanged("CodTipoClasePersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetallePoder {
            get {
                return this.DetallePoderField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallePoderField, value) != true)) {
                    this.DetallePoderField = value;
                    this.RaisePropertyChanged("DetallePoder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioField, value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreApoderado {
            get {
                return this.NombreApoderadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreApoderadoField, value) != true)) {
                    this.NombreApoderadoField = value;
                    this.RaisePropertyChanged("NombreApoderado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroCanton {
            get {
                return this.NroCantonField;
            }
            set {
                if ((this.NroCantonField.Equals(value) != true)) {
                    this.NroCantonField = value;
                    this.RaisePropertyChanged("NroCanton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroDistrito {
            get {
                return this.NroDistritoField;
            }
            set {
                if ((this.NroDistritoField.Equals(value) != true)) {
                    this.NroDistritoField = value;
                    this.RaisePropertyChanged("NroDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroIdentificacion {
            get {
                return this.NroIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NroIdentificacionField, value) != true)) {
                    this.NroIdentificacionField = value;
                    this.RaisePropertyChanged("NroIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroProvincia {
            get {
                return this.NroProvinciaField;
            }
            set {
                if ((this.NroProvinciaField.Equals(value) != true)) {
                    this.NroProvinciaField = value;
                    this.RaisePropertyChanged("NroProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtrasSenas {
            get {
                return this.OtrasSenasField;
            }
            set {
                if ((object.ReferenceEquals(this.OtrasSenasField, value) != true)) {
                    this.OtrasSenasField = value;
                    this.RaisePropertyChanged("OtrasSenas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrCanton {
            get {
                return this.StrCantonField;
            }
            set {
                if ((object.ReferenceEquals(this.StrCantonField, value) != true)) {
                    this.StrCantonField = value;
                    this.RaisePropertyChanged("StrCanton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrDistrito {
            get {
                return this.StrDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.StrDistritoField, value) != true)) {
                    this.StrDistritoField = value;
                    this.RaisePropertyChanged("StrDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrProvincia {
            get {
                return this.StrProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrProvinciaField, value) != true)) {
                    this.StrProvinciaField = value;
                    this.RaisePropertyChanged("StrProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoMovil {
            get {
                return this.TelefonoMovilField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoMovilField, value) != true)) {
                    this.TelefonoMovilField = value;
                    this.RaisePropertyChanged("TelefonoMovil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_InscripcionRUT.Models")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoClasePersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCierreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreContribuyenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroCantonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtrasSenasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrCantonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoFijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoMovilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTipoClasePersona {
            get {
                return this.CodTipoClasePersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoClasePersonaField, value) != true)) {
                    this.CodTipoClasePersonaField = value;
                    this.RaisePropertyChanged("CodTipoClasePersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCierre {
            get {
                return this.FechaCierreField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCierreField, value) != true)) {
                    this.FechaCierreField = value;
                    this.RaisePropertyChanged("FechaCierre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreContribuyente {
            get {
                return this.NombreContribuyenteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreContribuyenteField, value) != true)) {
                    this.NombreContribuyenteField = value;
                    this.RaisePropertyChanged("NombreContribuyente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroCanton {
            get {
                return this.NroCantonField;
            }
            set {
                if ((this.NroCantonField.Equals(value) != true)) {
                    this.NroCantonField = value;
                    this.RaisePropertyChanged("NroCanton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroDistrito {
            get {
                return this.NroDistritoField;
            }
            set {
                if ((this.NroDistritoField.Equals(value) != true)) {
                    this.NroDistritoField = value;
                    this.RaisePropertyChanged("NroDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroIdentificacion {
            get {
                return this.NroIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NroIdentificacionField, value) != true)) {
                    this.NroIdentificacionField = value;
                    this.RaisePropertyChanged("NroIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroProvincia {
            get {
                return this.NroProvinciaField;
            }
            set {
                if ((this.NroProvinciaField.Equals(value) != true)) {
                    this.NroProvinciaField = value;
                    this.RaisePropertyChanged("NroProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtrasSenas {
            get {
                return this.OtrasSenasField;
            }
            set {
                if ((object.ReferenceEquals(this.OtrasSenasField, value) != true)) {
                    this.OtrasSenasField = value;
                    this.RaisePropertyChanged("OtrasSenas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrCanton {
            get {
                return this.StrCantonField;
            }
            set {
                if ((object.ReferenceEquals(this.StrCantonField, value) != true)) {
                    this.StrCantonField = value;
                    this.RaisePropertyChanged("StrCanton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrDistrito {
            get {
                return this.StrDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.StrDistritoField, value) != true)) {
                    this.StrDistritoField = value;
                    this.RaisePropertyChanged("StrDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrProvincia {
            get {
                return this.StrProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrProvinciaField, value) != true)) {
                    this.StrProvinciaField = value;
                    this.RaisePropertyChanged("StrProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoFijo {
            get {
                return this.TelefonoFijoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoFijoField, value) != true)) {
                    this.TelefonoFijoField = value;
                    this.RaisePropertyChanged("TelefonoFijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoMovil {
            get {
                return this.TelefonoMovilField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoMovilField, value) != true)) {
                    this.TelefonoMovilField = value;
                    this.RaisePropertyChanged("TelefonoMovil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Representante", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_InscripcionRUT.Models")]
    [System.SerializableAttribute()]
    public partial class Representante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoClasePersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleRepresentacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroCantonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NroProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtrasSenasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrCantonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrNombreRepresentanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoMovilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTipoClasePersona {
            get {
                return this.CodTipoClasePersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoClasePersonaField, value) != true)) {
                    this.CodTipoClasePersonaField = value;
                    this.RaisePropertyChanged("CodTipoClasePersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetalleRepresentacion {
            get {
                return this.DetalleRepresentacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleRepresentacionField, value) != true)) {
                    this.DetalleRepresentacionField = value;
                    this.RaisePropertyChanged("DetalleRepresentacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioField, value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroCanton {
            get {
                return this.NroCantonField;
            }
            set {
                if ((this.NroCantonField.Equals(value) != true)) {
                    this.NroCantonField = value;
                    this.RaisePropertyChanged("NroCanton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroDistrito {
            get {
                return this.NroDistritoField;
            }
            set {
                if ((this.NroDistritoField.Equals(value) != true)) {
                    this.NroDistritoField = value;
                    this.RaisePropertyChanged("NroDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NroProvincia {
            get {
                return this.NroProvinciaField;
            }
            set {
                if ((this.NroProvinciaField.Equals(value) != true)) {
                    this.NroProvinciaField = value;
                    this.RaisePropertyChanged("NroProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumIdentificacion {
            get {
                return this.NumIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumIdentificacionField, value) != true)) {
                    this.NumIdentificacionField = value;
                    this.RaisePropertyChanged("NumIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtrasSenas {
            get {
                return this.OtrasSenasField;
            }
            set {
                if ((object.ReferenceEquals(this.OtrasSenasField, value) != true)) {
                    this.OtrasSenasField = value;
                    this.RaisePropertyChanged("OtrasSenas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrCanton {
            get {
                return this.StrCantonField;
            }
            set {
                if ((object.ReferenceEquals(this.StrCantonField, value) != true)) {
                    this.StrCantonField = value;
                    this.RaisePropertyChanged("StrCanton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrDistrito {
            get {
                return this.StrDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.StrDistritoField, value) != true)) {
                    this.StrDistritoField = value;
                    this.RaisePropertyChanged("StrDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrNombreRepresentante {
            get {
                return this.StrNombreRepresentanteField;
            }
            set {
                if ((object.ReferenceEquals(this.StrNombreRepresentanteField, value) != true)) {
                    this.StrNombreRepresentanteField = value;
                    this.RaisePropertyChanged("StrNombreRepresentante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrProvincia {
            get {
                return this.StrProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrProvinciaField, value) != true)) {
                    this.StrProvinciaField = value;
                    this.RaisePropertyChanged("StrProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoMovil {
            get {
                return this.TelefonoMovilField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoMovilField, value) != true)) {
                    this.TelefonoMovilField = value;
                    this.RaisePropertyChanged("TelefonoMovil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcomerRes", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_InscripcionRUT.Models")]
    [System.SerializableAttribute()]
    public partial class ProcomerRes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumCodSeguridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDeclaracionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumCodSeguridad {
            get {
                return this.NumCodSeguridadField;
            }
            set {
                if ((object.ReferenceEquals(this.NumCodSeguridadField, value) != true)) {
                    this.NumCodSeguridadField = value;
                    this.RaisePropertyChanged("NumCodSeguridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDeclaracion {
            get {
                return this.NumDeclaracionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDeclaracionField, value) != true)) {
                    this.NumDeclaracionField = value;
                    this.RaisePropertyChanged("NumDeclaracion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_ServicesRUTPruebas.IInscripcionRUT")]
    public interface IInscripcionRUT {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscripcionRUT/RealizaInscripcion", ReplyAction="http://tempuri.org/IInscripcionRUT/RealizaInscripcionResponse")]
        ServicioRUT.WS_ServicesRUTPruebas.ProcomerRes RealizaInscripcion(ServicioRUT.WS_ServicesRUTPruebas.ProcomerReq procomerReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscripcionRUT/RealizaInscripcion", ReplyAction="http://tempuri.org/IInscripcionRUT/RealizaInscripcionResponse")]
        System.Threading.Tasks.Task<ServicioRUT.WS_ServicesRUTPruebas.ProcomerRes> RealizaInscripcionAsync(ServicioRUT.WS_ServicesRUTPruebas.ProcomerReq procomerReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscripcionRUT/RealizaInscripcionJson", ReplyAction="http://tempuri.org/IInscripcionRUT/RealizaInscripcionJsonResponse")]
        string RealizaInscripcionJson(string jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscripcionRUT/RealizaInscripcionJson", ReplyAction="http://tempuri.org/IInscripcionRUT/RealizaInscripcionJsonResponse")]
        System.Threading.Tasks.Task<string> RealizaInscripcionJsonAsync(string jsonData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInscripcionRUTChannel : ServicioRUT.WS_ServicesRUTPruebas.IInscripcionRUT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InscripcionRUTClient : System.ServiceModel.ClientBase<ServicioRUT.WS_ServicesRUTPruebas.IInscripcionRUT>, ServicioRUT.WS_ServicesRUTPruebas.IInscripcionRUT {
        
        public InscripcionRUTClient() {
        }
        
        public InscripcionRUTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InscripcionRUTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InscripcionRUTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InscripcionRUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicioRUT.WS_ServicesRUTPruebas.ProcomerRes RealizaInscripcion(ServicioRUT.WS_ServicesRUTPruebas.ProcomerReq procomerReq) {
            return base.Channel.RealizaInscripcion(procomerReq);
        }
        
        public System.Threading.Tasks.Task<ServicioRUT.WS_ServicesRUTPruebas.ProcomerRes> RealizaInscripcionAsync(ServicioRUT.WS_ServicesRUTPruebas.ProcomerReq procomerReq) {
            return base.Channel.RealizaInscripcionAsync(procomerReq);
        }
        
        public string RealizaInscripcionJson(string jsonData) {
            return base.Channel.RealizaInscripcionJson(jsonData);
        }
        
        public System.Threading.Tasks.Task<string> RealizaInscripcionJsonAsync(string jsonData) {
            return base.Channel.RealizaInscripcionJsonAsync(jsonData);
        }
    }
}
